# Generated by Django 2.0.6 on 2018-06-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180619_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='assets/images/no-img.jpg', upload_to='assets/images/'),
        ),
    ]
